apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: nourkaroui/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: nourkaroui/donate
      context: donate
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.*'
            dest: .
